create table LANGUAGE (ID IDENTITY NOT NULL, PATH VARCHAR NOT NULL, NAME VARCHAR NOT NULL, CREATED TIMESTAMP NOT NULL DEFAULT now(), UPDATED TIMESTAMP NOT NULL DEFAULT now(), PRIMARY KEY (ID));
create table SNIPPET (ID IDENTITY NOT NULL, LANGUAGE_ID INTEGER NOT NULL, TITLE VARCHAR NOT NULL, CONTENT VARCHAR NOT NULL, CREATED TIMESTAMP NOT NULL DEFAULT now(), UPDATED TIMESTAMP NOT NULL DEFAULT now(), PRIMARY KEY (ID));
create table COMMENT (ID IDENTITY NOT NULL, SNIPPET_ID INTEGER NOT NULL, NAME VARCHAR NOT NULL, TEXT VARCHAR NOT NULL, CREATED TIMESTAMP NOT NULL DEFAULT now(), UPDATED TIMESTAMP NOT NULL DEFAULT now(), PRIMARY KEY (ID));

insert into LANGUAGE values (1, 'java', 'Java', now(), now());
insert into LANGUAGE values (2, 'perl', 'Perl', now(), now());

-- insert into SNIPPET values (1, 1, 'Java Dummy Title1', 'this is content1', now(), now());
-- insert into SNIPPET values (2, 1, 'Java Dummy nTitle2', 'this is content2', now(), now());
